export default [
  ['', '', '', '', '', '', '', '', '', ''],
  [
    '1',
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule"
  ],
  [
    '2',
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule",
    "REV'N Web Feed Schedule"
  ],
  [
    '3',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022',
    'All times Eastern / Effective September 26, 2022'
  ],
  [
    '4',
    'Time',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
    'Sunday',
    'Time'
  ],
  [
    '5',
    '12:00 AM',
    'Lokar Car Show',
    'V8TV',
    'Car Guy Show; The',
    'The American Car Prospector',
    'Lokar Car Show',
    'The Appraisers',
    'OPGI American Classics',
    '12:00 AM'
  ],
  [
    '6',
    '12:30 AM',
    'Outlaw Truck and Tractor',
    'Inside Drag Racing',
    'Inside Drag Racing',
    'The American Car Prospector',
    'Inside Drag Racing',
    'Inside Drag Racing',
    'Motorz',
    '12:30 AM'
  ],
  [
    '7',
    '1:00 AM',
    'Cruise-In',
    'World of Speed & Beauty',
    'World of Speed & Beauty',
    'World of Speed & Beauty',
    'World of Speed & Beauty',
    'World of Speed & Beauty',
    'What Would Mike Do?',
    '1:00 AM'
  ],
  [
    '8',
    '1:30 AM',
    'Motor Mania',
    'Car Guy Show; The',
    'Hooked On Dirt',
    'Dream Car Garage',
    'Dream Ridez',
    'Motorhead Garage',
    'NHRA Pro Mod Series',
    '1:30 AM'
  ],
  [
    '9',
    '2:00 AM',
    "Sam's Garage",
    "Sam's Garage",
    "Sam's Garage",
    "Sam's Garage",
    "Sam's Garage",
    "Sam's Garage",
    "Sam's Garage",
    '2:00 AM'
  ],
  [
    '10',
    '2:30 AM',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    '2:30 AM'
  ],
  [
    '11',
    '3:00 AM',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    "Rev'n News",
    'Car Guy Show; The',
    '3:00 AM'
  ],
  [
    '12',
    '3:30 AM',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Motor Mania',
    'Dream Ridez',
    '3:30 AM'
  ],
  [
    '13',
    '4:00 AM',
    'World of Trucks',
    'World of Trucks',
    'World of Trucks',
    'World of Trucks',
    'World of Trucks',
    'Formula One Drift',
    'Lokar Car Show',
    '4:00 AM'
  ],
  [
    '14',
    '4:30 AM',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    "Mother's Car Show",
    'Classic Cars',
    '4:30 AM'
  ],
  [
    '15',
    '5:00 AM',
    'Motorhead Garage',
    "Boats n' Bikes",
    'Dream Ridez',
    'Car Guy Show; The',
    'Top Dead Center',
    'Off Road Action',
    "Boats n' Bikes",
    '5:00 AM'
  ],
  [
    '16',
    '5:30 AM',
    'Top Dead Center',
    'What Would Mike Do?',
    'My Classic Car',
    'Pleasure Boater',
    'Formula One Drift',
    'My Classic Car',
    'World of Trucks',
    '5:30 AM'
  ],
  [
    '17',
    '6:00 AM',
    'The Amazing World of Automobiles',
    'Bidding Wars',
    'The American Car Prospector',
    'Classic Cars',
    'Flying Through Time',
    "Sam's Garage",
    "Trippin' on Two Wheels",
    '6:00 AM'
  ],
  [
    '18',
    '6:30 AM',
    'The Amazing World of Automobiles',
    'Car Guy Show; The',
    'The American Car Prospector',
    'Hooked On Dirt',
    'Flying Through Time',
    "Boats n' Bikes",
    "Trippin' on Two Wheels",
    '6:30 AM'
  ],
  [
    '19',
    '7:00 AM',
    'Cruise-In',
    "Rev'n News",
    'Motorhead Garage',
    '1000cc Raw Thrill',
    'Racing Through Time',
    'Pleasure Boater',
    'Intrepid Powerboats On the Water',
    '7:00 AM'
  ],
  [
    '20',
    '7:30 AM',
    'Hooked On Dirt',
    'Motorz',
    'Tech Garage',
    'Lokar Car Show',
    'Racing Through Time',
    'Intrepid Powerboats On the Water',
    'Bidding Wars',
    '7:30 AM'
  ],
  [
    '21',
    '8:00 AM',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'The American Car Prospector',
    'Dream Ridez',
    '8:00 AM'
  ],
  [
    '22',
    '8:30 AM',
    'Car Files',
    'Car Files',
    'Car Files',
    'Car Files',
    'Car Files',
    'The American Car Prospector',
    "Sam's Garage",
    '8:30 AM'
  ],
  [
    '23',
    '9:00 AM',
    'Intrepid Powerboats On the Water',
    'Pleasure Boater',
    "Sam's Garage",
    'Tech Garage',
    "Boats n' Bikes",
    'OPGI American Classics',
    "Boats n' Bikes",
    '9:00 AM'
  ],
  [
    '24',
    '9:30 AM',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    '1000cc Raw Thrill',
    'World of Trucks',
    '9:30 AM'
  ],
  [
    '25',
    '10:00 AM',
    "The Curator's Vault",
    'Reality Rides',
    "The Curator's Vault",
    'Reality Rides',
    "The Curator's Vault",
    'My Classic Car',
    'Intrepid Powerboats On the Water',
    '10:00 AM'
  ],
  [
    '26',
    '10:30 AM',
    'Reality Rides',
    'Reality Rides',
    'Reality Rides',
    'Reality Rides',
    'Reality Rides',
    'My Classic Car',
    'Pleasure Boater',
    '10:30 AM'
  ],
  [
    '27',
    '11:00 AM',
    'Motor Week',
    'Motor Week',
    'Motor Week',
    'Motor Week',
    'Motor Week',
    'Lund International Truck and Jeep Show',
    'Race Central TV',
    '11:00 AM'
  ],
  [
    '28',
    '11:30 AM',
    'Lund International Truck and Jeep Show',
    'Hooked On Dirt',
    "America's 4 X 4 Invasion",
    'Brand New Musicle Car: Yenko Camero',
    'Hot Rod Madness',
    'All Out Racing',
    '1000cc Raw Thrill',
    '11:30 AM'
  ],
  [
    '29',
    '12:00 PM',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'American Car Prospector; The',
    'Grassroots Racing',
    '12:00 PM'
  ],
  [
    '30',
    '12:30 PM',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'American Car Prospector; The',
    'Kits-N-Cruisin',
    '12:30 PM'
  ],
  [
    '31',
    '1:00 PM',
    "The Curator's Vault",
    'Reality Rides',
    "The Curator's Vault",
    'Reality Rides',
    "The Curator's Vault",
    'Performance TV',
    'Performance TV',
    '1:00 PM'
  ],
  [
    '32',
    '1:30 PM',
    'Reality Rides',
    'Reality Rides',
    'Reality Rides',
    'Reality Rides',
    'Reality Rides',
    "Boats n' Bikes",
    'V8TV',
    '1:30 PM'
  ],
  [
    '33',
    '2:00 PM',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'Superlift Off-Road Adventures',
    'Intrepid Powerboats On the Water',
    'The Amazing World of Automobiles',
    '2:00 PM'
  ],
  [
    '34',
    '2:30 PM',
    'Lund International Truck and Jeep Show',
    'Hooked On Dirt',
    "America's 4 X 4 Invasion",
    'Brand New Musicle Car: Yenko Camero',
    'Hot Rod Madness',
    'Pleasure Boater',
    'The Amazing World of Automobiles',
    '2:30 PM'
  ],
  [
    '35',
    '3:00 PM',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Performance TV',
    'Hot Rod Madness',
    'Car Guy Show; The',
    '3:00 PM'
  ],
  [
    '36',
    '3:30 PM',
    'Lokar Car Show',
    'Lokar Car Show',
    'Lokar Car Show',
    'Lokar Car Show',
    'Lokar Car Show',
    'Grassroots Racing',
    'My Classic Car',
    '3:30 PM'
  ],
  [
    '37',
    '4:00 PM',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    'Motorhead Garage',
    'Lokar Car Show',
    'OPGI American Classics',
    '4:00 PM'
  ],
  [
    '38',
    '4:30 PM',
    'Brand New Musicle Car: Yenko Camero',
    'Pleasure Boater',
    'Tech Garage',
    'V8TV',
    'Lund International Truck and Jeep Show',
    "Mother's Car Show",
    'Lokar Car Show',
    '4:30 PM'
  ],
  [
    '39',
    '5:00 PM',
    'OPGI American Classics',
    "Boats n' Bikes",
    "Sam's Garage",
    'Top Ten Auto Show',
    'Flying Through Time',
    'Brand New Musicle Car: Yenko Camero',
    'Racing Through Time',
    '5:00 PM'
  ],
  [
    '40',
    '5:30 PM',
    'Lund International Truck and Jeep Show',
    'Reverend Bob Torque Show',
    'Dream Car Garage',
    'Pleasure Boater',
    'Flying Through Time',
    'My Classic Car',
    'Racing Through Time',
    '5:30 PM'
  ],
  [
    '41',
    '6:00 PM',
    'The Amazing World of Automobiles',
    'Bidding Wars',
    'On Two Wheels',
    'Classic Cars',
    'Racing Through Time',
    "Sam's Garage",
    'Flying Through Time',
    '6:00 PM'
  ],
  [
    '42',
    '6:30 PM',
    'The Amazing World of Automobiles',
    'Classic Cars',
    'On Two Wheels',
    'Hooked On Dirt',
    'Racing Through Time',
    'Men & Motors Showcase',
    'Flying Through Time',
    '6:30 PM'
  ],
  [
    '43',
    '7:00 PM',
    'Cruise-In',
    'Performance TV',
    'Motorhead Garage',
    'Grand Quiz Auto',
    '400 Thunder Premium Races',
    "Boats n' Bikes",
    'Intrepid Powerboats On the Water',
    '7:00 PM'
  ],
  [
    '44',
    '7:30 PM',
    'Hooked On Dirt',
    'Motorz',
    'Tech Garage',
    "America's 4 X 4 Invasion",
    '400 Thunder Premium Races',
    'Intrepid Powerboats On the Water',
    'Hot Rod Madness',
    '7:30 PM'
  ],
  [
    '45',
    '8:00 PM',
    'Operation Repo',
    'Operation Repo',
    'Operation Repo',
    'Operation Repo',
    'Operation Repo',
    'Pleasure Boater',
    'Motorhead Garage',
    '8:00 PM'
  ],
  [
    '46',
    '8:30 PM',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'My Classic Car',
    'The Appraisers',
    'Lokar Car Show',
    '8:30 PM'
  ],
  [
    '47',
    '9:00 PM',
    'American Car Prospector; The',
    'Auto Files',
    "Sam's Garage",
    'Lokar Car Show',
    'The Appraisers',
    'Performance TV',
    '400 Thunder Premium Races',
    '9:00 PM'
  ],
  [
    '48',
    '9:30 PM',
    'American Car Prospector; The',
    'Pit Stop',
    'Kits-N-Cruisin',
    'OPGI American Classics',
    'Classic Cars',
    "Sam's Garage",
    '400 Thunder Premium Races',
    '9:30 PM'
  ],
  [
    '49',
    '10:00 PM',
    'Cruise-In',
    '400 Thunder Premium Races',
    'Motorhead Garage',
    'King of the Road',
    'Hot Rod Madness',
    'The Car Guy Show',
    'Performance TV',
    '10:00 PM'
  ],
  [
    '50',
    '10:30 PM',
    'Hooked On Dirt',
    '400 Thunder Premium Races',
    'Tech Garage',
    "America's 4 X 4 Invasion",
    'Brand New Muscle Car: Yenko Camaro',
    'Dream Car Garage',
    'The Appraisers',
    '10:30 PM'
  ],
  [
    '51',
    '11:00 PM',
    'Operation Repo',
    'Operation Repo',
    'Operation Repo',
    'Operation Repo',
    'Operation Repo',
    'Cruise-In',
    'Motorhead Garage',
    '11:00 PM'
  ],
  [
    '52',
    '11:30 PM',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'Dream Car Garage',
    'The Appraisers',
    'Tech Garage',
    '11:30 PM'
  ]
]
